<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {     if($this->session->userdata('logged_in'))
                {
                  $session_data = $this->session->userdata('logged_in');
                  $data['nom'] = $session_data['nom'];
                  $data['prenom'] = $session_data['prenom'];
                  $data['email'] = $session_data['email'];
				  $data['role'] = $session_data['role'];
				  
        $data['users'] = $this->User_model->get_all_users();

        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
		
			}
          else
                {
                  //If no session, redirect to login page
                  redirect(site_url('login'), 'refresh');
                }
    }

    /*
     * Adding a new user
     */
    function add()
	
	
    {   
	
	 if($this->session->userdata('logged_in'))
                {
                  $session_data = $this->session->userdata('logged_in');
                  $data['nom'] = $session_data['nom'];
                  $data['prenom'] = $session_data['prenom'];
                  $data['email'] = $session_data['email'];
				  $data['role'] = $session_data['role'];
				  
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nom' => $this->input->post('nom'),
				'prenom' => $this->input->post('prenom'),
				'email' => $this->input->post('email'),
				'mdp' => $this->input->post('mdp'),
				'role' => $this->input->post('role'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
			}
          else
                {
                  //If no session, redirect to login page
                  redirect(site_url('login'), 'refresh');
                }
    }  

    /*
     * Editing a user
     */
    function edit($id)
    {   
	
	 if($this->session->userdata('logged_in'))
                {
                  $session_data = $this->session->userdata('logged_in');
                  $data['nom'] = $session_data['nom'];
                  $data['prenom'] = $session_data['prenom'];
                  $data['email'] = $session_data['email'];
				  $data['role'] = $session_data['role'];
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id);
        
        if(isset($data['user']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nom' => $this->input->post('nom'),
					'prenom' => $this->input->post('prenom'),
					'email' => $this->input->post('email'),
					'mdp' => $this->input->post('mdp'),
					'role' => $this->input->post('role'),
                );

                $this->User_model->update_user($id,$params);            
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
		
			}
          else
                {
                  //If no session, redirect to login page
                  redirect(site_url('login'), 'refresh');
                }
    } 

    /*
     * Deleting user
     */
    function remove($id)
    { 
	 if($this->session->userdata('logged_in'))
                {
                  $session_data = $this->session->userdata('logged_in');
                  $data['nom'] = $session_data['nom'];
                  $data['prenom'] = $session_data['prenom'];
                  $data['email'] = $session_data['email'];
				  $data['role'] = $session_data['role'];
				  
        $user = $this->User_model->get_user($id);

        // check if the user exists before trying to delete it
        if(isset($user['id']))
        {
            $this->User_model->delete_user($id);
            redirect('user/index');
        }
        else{
            show_error('The user you are trying to delete does not exist.');
			}
    	}
          else
                {
                  //If no session, redirect to login page
                  redirect(site_url('login'), 'refresh');
                }
}
}
