<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Logs_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
   
    /*
     * Get all agents
     */
    function get_all_logs()
    {
        return $this->db->get('logs')->result_array();
    }

  
   
}
